### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by ahmadia** [rainwoodman/python-mpi-bcast#1]
What is the license for this project?  I'd suggest Python-traditional BSD or MIT.

**Comment by rainwoodman** [comment]
Thanks. Since mpi4py is BSD, I will go along with BSD.

**Comment by ahmadia** [comment]
Sounds good.  Would you like a PR for this or can you take it from here? :)

**Comment by rainwoodman** [comment]
Thanks. I just added a License based on the one at https://github.com/erdc-cm/mpi4py/blob/master/LICENSE.txt Fixed a few typos and a missing commit meanwhile. :)
. 
Does this look correct? Is there a newer version of BSD license that we shall use?

**Comment by ahmadia** [comment]
Looks good to me.  Note that the official mpi4py repository is at https://bitbucket.org/mpi4py/mpi4py, the ERDC-CM one is a fork.  License/attribution all looks fine to me.  cc @dalcinl

**Comment by ahmadia** [comment]
Oops, Lisandro just pointed out that the official repo is at BitBucket, not GitHub, fixed the above URL.

**Comment by rainwoodman** [comment]
Yes. The official repo is at BitBucket, and the ERDC-CM fork is the first that pops out on google with 'mpi4py license'. I just checked the license are the same on both locations. 

So we have a BSD license now.
